name: Go

on: 
  push:
    tags:
      - 'v*'

permissions:
  contents: write 


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.24' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version

      - name: Install dependencies
        run: go mod download
      
      - name: Lint
        run: go vet ./... 

      - name: Format
        run: go fmt ./...

      - name: Run tests
        run: go test -v ./...

      - name: Build
        run: go build -o hello-world .

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: 
            hello-world
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_SHA: ${{ github.sha }}


      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Extract version from tag
        id: extract_tag
        run: echo "VERSION=${GITHUB_REF##*/}" >> "$GITHUB_ENV"


      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:${{ env.VERSION }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:${{ env.VERSION }}




